# Generated by Django 3.0.1 on 2020-02-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=300)),
                ('star', models.IntegerField(max_length=5)),
                ('pid', models.IntegerField(max_length=20)),
            ],
        ),
    ]
