# Generated by Django 3.0.1 on 2020-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHones', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='udate',
            field=models.DateField(auto_now=True),
        ),
    ]
