# Generated by Django 3.0.1 on 2020-03-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHones', '0003_feedback_udate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
