# Generated by Django 3.0.1 on 2020-01-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200115_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.CharField(max_length=200)),
                ('pcategory', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=200)),
                ('harddisk', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pimg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.CharField(max_length=200)),
                ('pcategory', models.CharField(max_length=50)),
                ('pscategory', models.CharField(default='', max_length=100)),
                ('memory', models.CharField(max_length=200)),
                ('camera', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pimg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product Name', models.CharField(max_length=50)),
                ('Product Description', models.CharField(max_length=200)),
                ('Product Category', models.CharField(max_length=50)),
                ('Resolution', models.CharField(max_length=200)),
                ('USB', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
