# Generated by Django 3.0.1 on 2020-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200115_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='HardDisk',
            new_name='harddisk',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Memory',
            new_name='memory',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Product Category',
            new_name='pcategory',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Product Description',
            new_name='pdesc',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Image',
            new_name='pimg',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Camera',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Product Category',
            new_name='pcategory',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Product Description',
            new_name='pdesc',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Image',
            new_name='pimg',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='tvs',
            old_name='Product Category',
            new_name='pcategory',
        ),
        migrations.RenameField(
            model_name='tvs',
            old_name='Product Description',
            new_name='pdesc',
        ),
        migrations.RenameField(
            model_name='tvs',
            old_name='Image',
            new_name='pimg',
        ),
        migrations.RenameField(
            model_name='tvs',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='tvs',
            old_name='Resolution',
            new_name='resolution',
        ),
        migrations.RenameField(
            model_name='tvs',
            old_name='USB',
            new_name='usb',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='Product Name',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='Product Name',
        ),
        migrations.RemoveField(
            model_name='tvs',
            name='Product Name',
        ),
        migrations.AddField(
            model_name='laptop',
            name='pname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='phone',
            name='pname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tvs',
            name='pname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
