# Generated by Django 3.0.1 on 2020-01-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200115_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=50)),
                ('pdesc', models.CharField(max_length=200)),
                ('pcategory', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pimg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Battery',
            new_name='battery',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Memory',
            new_name='memory',
        ),
    ]
