# Generated by Django 3.0.1 on 2020-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200122_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uname', models.CharField(default='', max_length=50)),
                ('upass', models.CharField(default='', max_length=50)),
                ('uemail', models.EmailField(max_length=254)),
                ('uadd', models.CharField(default='', max_length=150)),
                ('uphone', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
