# Generated by Django 3.0.1 on 2020-01-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200125_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
