# Generated by Django 3.0.1 on 2020-01-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Tvs',
        ),
    ]
