# Generated by Django 3.0.1 on 2020-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200317_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
