# Generated by Django 3.0.1 on 2020-03-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200317_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='uname',
            new_name='Username',
        ),
        migrations.AlterField(
            model_name='users',
            name='uadd',
            field=models.CharField(default='', max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upass',
            field=models.CharField(default='', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Phone'),
        ),
    ]
