# Generated by Django 3.0.1 on 2020-03-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200317_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Username',
            new_name='uname',
        ),
        migrations.AlterField(
            model_name='users',
            name='upass',
            field=models.CharField(default='', max_length=150, verbose_name='Password'),
        ),
    ]
