# Generated by Django 3.0.1 on 2020-03-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200317_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(default='', max_length=200, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='users',
            name='zip',
            field=models.IntegerField(default=0, max_length=6, verbose_name='ZipCode'),
            preserve_default=False,
        ),
    ]
