# Generated by Django 3.0.1 on 2020-03-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200318_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Phone'),
        ),
    ]
