# Generated by Django 3.0.1 on 2020-03-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200319_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jsondata',
            field=models.CharField(default='blank', max_length=1000),
        ),
    ]
