# Generated by Django 3.0.1 on 2020-03-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200319_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custid',
        ),
    ]
