# Generated by Django 3.0.1 on 2020-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_order_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(auto_now=True),
        ),
    ]
