# Generated by Django 3.0.1 on 2020-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20200320_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
