# Generated by Django 3.0.1 on 2020-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200324_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jsondata',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
