# Generated by Django 3.0.1 on 2020-01-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=50)),
                ('pdesc', models.CharField(max_length=200)),
                ('pcategory', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=200)),
                ('harddisk', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pimg', models.ImageField(upload_to='')),
            ],
        ),
    ]
